{
  "contest": 393,
  "handle": "shaflow2",
  "risk": "3",
  "title": "ClaimRefund function can never succeed",
  "issueId": 38,
  "issueUrl": "https://github.com/code-423n4/2024-06-vultisig-findings/issues/38"
}